name: Build/release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: false

  build:
    name: build_release
    needs: create_release
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            release_suffix: windows
            release_format: exe
          - os: ubuntu-latest
            release_suffix: ubuntu
            release_format: deb
#          - os: macos-latest
#            release_suffix: macos
#            release_format: dmg
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    
    - run: yarn install
    - run: yarn run electron:package:${{ matrix.os }}

    - name: Upload .${{ matrix.release_format }} file
      uses: actions/upload-artifact@v3
      with:
        name: nft_viewer.${{ matrix.release_format }}
        path: dist/nft_viewer.${{ matrix.release_format }}

  generate:
    name: generate files
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download exe
      id: download
      uses: actions/download-artifact@v3
      with:
        name: nft_viewer.exe
        path: ~/
    - name: Download deb
      uses: actions/download-artifact@v3
      with:
        name: nft_viewer.deb
        path: ~/
    - name: Calculate hashes
      id: calc_hash
      run: |
          echo "::set-output name=debhash::$(sha256sum /home/runner/nft_viewer.deb|cut -c-64)"
          echo "::set-output name=exehash::$(sha256sum /home/runner/nft_viewer.exe|cut -c-64)"
    - name: Perform release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            /home/runner/nft_viewer.exe
            /home/runner/nft_viewer.deb
        tag_name: ${{ needs.create_release.outputs.tag-name }}
        body: |
                Release Notes
                _________________________________
                Binaries for download
                --------
                | Platform | SHA256 Checksum |
                |---|---|
                |[Microsoft Windows](https://github.com/BTS-CM/NFT_Viewer/releases/download/${{ github.ref_name }}/nft_viewer.exe)|`${{steps.calc_hash.outputs.exehash}}`|
                |[Linux](https://github.com/BTS-CM/NFT_Viewer/releases/download/${{ github.ref_name }}/nft_viewer.deb)|`${{steps.calc_hash.outputs.debhash}}`|
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: VirusTotal Monitor Scan
      uses: grctest/ghaction-virustotal@71d4987c5988ab43392f3cc38e00b32e039b494e
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        vt_monitor: true
        request_rate: 1
        monitor_path: /home/runner/
        files: |
          /home/runner/nft_viewer.exe
          /home/runner/nft_viewer.deb